name: Build Python Package

on:
  workflow_dispatch:

jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Attest build provenance
        uses: actions/attest@bdehamer/error-detail
        with:
          subject-name: foo
          subject-digest: sha256:62ce42bde6b4ba3aa0c42aa375025015b639b142c9b4daf89fcd422fc75f4a13
          predicate-type: bar/bar
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build package
        run: python -m build .

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist/*.whl"

      - name: Generate SBOM
        uses: anchore/sbom-action@v0.15.11
        with:
          format: "spdx-json"
          output-file: "sbom.spdx.json"

      - name: Attest SBOM
        uses: actions/attest-sbom@v1
        with:
          subject-path: "dist/*.whl"
          sbom-path: "sbom.spdx.json"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: "dist/*.whl"

  verify:
    name: verify package
    needs: build
    runs-on: ubuntu-latest
    permissions:
      attestations: read
      contents: read

    steps:
      # Need to checkout and build gh CLI until the latest version with v0.3
      # attestation bundle support is released
      - name: Checkout cli/cli
        uses: actions/checkout@v4
        with:
          repository: cli/cli
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Download dependencies
        run: go mod download
      - name: Build cli
        run: make bin/gh

      - name: Retrieve build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Verify build artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./bin/gh attestation verify *.whl --owner "$GITHUB_REPOSITORY_OWNER"
