name: Build Python Package

on:
  workflow_dispatch:

jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build package
        run: python -m build .

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist/*.whl"

      - name: Generate SBOM
        uses: anchore/sbom-action@v0.15.11
        with:
          format: "spdx-json"
          output-file: "sbom.spdx.json"

      - name: Attest SBOM
        uses: actions/attest-sbom@v1
        with:
          subject-path: "dist/*.whl"
          sbom-path: "sbom.spdx.json"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: "dist/*.whl"
