name: Attest w/ Push

on:
  workflow_dispatch:

jobs:
  attest-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Attest artifact
        uses: actions/attest@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: sha256:358e52976b041df295e2de3b370168c387e91e78a3ecf813c6db66c37590440c
          predicate-type: application/json
          predicate: ${{ toJson(github) }}
          push-to-registry: true

